apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
      - name: mailer-service
        image: "zuraterloeva/mailer-service:latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MAILER_DOMAIN
            value: "localhost"
          - name: MAILER_HOST
            value: "mailhog"
          - name: MAILER_PORT
            value: "1025"
          - name: MAILER_ENCRYPTION
            value: "none"
          - name: MAILER_USERNAME
            value: ""
          - name: MAILER_PASSWORD
            value: ""
          - name: FROM_NAME
            value: "User"
          - name: FROM_ADDRESS
            value: "user@gmail.com"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
